/** W1.1: onboarding, app shell, hive picker, common chrome, quit/recovery. */
export const w1_1_en = {
  status: { idle: 'idle', working: 'working', waiting: 'waiting', needsYou: 'needs you', done: 'done', gone: 'gone', compacting: 'compacting', looping: 'looping', yourDraft: 'your draft' },
  onboarding: {
    title: { persona: 'WELCOME TO MUNDER DIFFLIN', welcome: 'MEET YOUR OFFICE', home: 'STEP 1 OF 4 · HARNESS HOME', homePlain: 'STEP 1 OF 4 · A HOME FOR THE APP', orchestrator: "STEP 2 OF 4 · YOUR CLONE'S ENGINE", orchestratorPlain: 'STEP 2 OF 4 · YOUR CLONE', repos: 'STEP 3 OF 4 · YOUR REPOS', reposPlain: 'STEP 3 OF 4 · YOUR PROJECTS', permissions: 'STEP 4 OF 4 · PERMISSIONS & RELIABILITY', done: 'ALL SET' },
    cloneTitle: 'A CLONE OF YOU, WORKING 24/7',
    cloneIntro: "Munder Difflin turns the CLI agent you already use into a clone of you — one that runs an office of long-running agents and keeps working while you're away. It manages everything around them: context, memory, tasks, triggers, environment, files, and integrations.",
    localOnly: 'Everything runs on this machine.',
    personaPrompt: "FIRST — WHO ARE YOU? (we'll tailor the setup)", technical: "I'M TECHNICAL", technicalDesc: 'I write code or work in a terminal. Show me CLI commands, flags, and model ids.', nonTechnical: "I'M NON-TECHNICAL", nonTechnicalDesc: "I'm in marketing, sales, ops, or just starting out. Explain things in plain language.",
    officeTitle: 'YOUR CLONE AND THE FLOOR IT RUNS', officePlain: "Your clone runs a small office of AI workers, and you watch it all from one screen. Here's what's inside:", officeTechnical: "Your clone coordinates a hive of AI coding agents — persistent, watchable, all local. Here's what's inside:",
    feature: {
      engines: { label: 'TEN ENGINES, ONE OFFICE', technical: 'Claude Code, Codex, Grok, Kimi, Antigravity, Qwen, OpenCode, Crush, pi & Copilot — live agents on one floor.', plain: 'Ten AI assistants — Claude, Codex, Gemini, Grok and more — working side by side in one shared office.' },
      clone: { label: 'MICHAEL IS YOUR CLONE', technical: 'Your clone runs the floor — triages requests, routes tasks, and escalates only what needs you.', plain: 'Your clone, Michael, takes your requests, hands work to the right agent, and only interrupts you when it matters.' },
      memory: { label: 'LONG-TERM MEMORY', technical: 'Each agent keeps notes, mined into a shared, searchable MemPalace.', plain: "Agents remember what they've done, so they don't start from scratch every time." },
      command: { label: 'COMMAND CENTER', technical: 'Terminal · Floor · Memory · Activity · Tasks · Triggers in one control surface.', plain: "One dashboard to watch the work, the agents' memory, tasks, and triggers." },
      guardrails: { label: 'GUARDRAILS', technical: 'Per-agent token budgets, a steer→constrain→stop circuit breaker, and human approvals.', plain: 'Spending limits and safety stops keep agents in check — and they can ask you before big actions.' },
      hires: { label: 'READY-MADE HIRES', technical: 'Grab a pre-configured agent from the Agent Gallery and spawn it in one click.', plain: 'Hire a ready-made agent from the gallery in one click — no setup needed.' }
    },
    homePlain: "Create a new, empty folder for the app to call home. Everything the app remembers — its own settings and your agents' memory — is stored here. Something like ~/HarnessAgents works well. We'll create it for you if it doesn't exist.",
    homeTechnical: "Pick a folder where the harness will keep its own files — agent metadata, logs, and any new repos you create from here. Something like ~/HarnessAgents is a fine default. We'll create it if it doesn't exist.",
    pickHome: 'pick', createPick: 'create / pick', homeHintPlain: "You won't need to open this folder day-to-day — it's just where the app keeps its notes so nothing is lost when you restart.", homeHintTechnical: 'Think of this as the "town hall." The harness pins agent state there so sessions can be picked back up after a restart.',
    orchestratorPlain: "Michael is your clone — he reads your requests, breaks them into tasks, and hands them to the right agent. He's the boss of the floor; you're still the boss of him. Choose which AI engine powers him.", orchestratorTechnical: 'Michael is your clone — the boss of the floor you just met. He triages your requests, assigns tasks, and manages the team, while escalating anything that genuinely needs you. Pick the engine and model that power him; give him a longer-context, higher-capability model.',
    cliPlain: 'A CLI agent is an AI coding assistant that runs on your computer — popular ones are Claude Code (Anthropic), Codex (OpenAI) and Antigravity (Google Gemini). Your clone is the always-on one that runs your whole office. We recommend Claude Code on Opus 4.8 (1M). You can add or switch the others later.',
    cliTechnical: 'Each option is a CLI engine you have installed (Claude Code, Codex, Antigravity/Gemini, or a local proxy like Qwen). Your clone (Michael) is the engine that orchestrates the whole hive. Recommended: Claude Code · Opus 4.8 · 1M — other providers can be wired per agent later.',
    recommended: 'RECOMMENDED', model: 'Model', modelHint: "This only sets Michael's engine. You can run other providers per agent later.",
    reposPlain: 'Add your projects. A project is simply a folder — it can hold code, documents, notes, or any files you want your agents to work with. You can create a brand-new folder or pick an existing one, and add more anytime.', reposTechnical: 'Add the repos you want your agents to work in. Each folder becomes a project (a room on the floor) — multiple agents can share one. You can add more later.', noProjects: 'No projects added yet. Optional — you can add one later.', noRepos: 'No repos added yet. Optional, but recommended.', addProject: 'add a project', addRepo: 'add a repo',
    autonomy: 'HOW MUCH CAN AGENTS DO ON THEIR OWN?', autonomyPlain: 'LET AGENTS WORK ON THEIR OWN', autonomyTechnical: 'WORK AUTONOMOUSLY (AUTO MODE)', autoOnPlain: 'On. Agents carry out tasks without stopping to ask — the smoothest experience.', autoOffPlain: 'Off. Agents pause and ask you before changing files or running commands.', autoOnTechnical: 'On. Agents never pause — Claude runs bypassPermissions, Codex bypasses approvals + sandbox, etc.', autoOffTechnical: 'Off. Each agent asks before edits / shell commands (Claude default, codex -a untrusted, …).', autoHintPlain: 'Keep this off until you trust the project and task. You can enable it later, including for individual agents.', autoHintTechnical: 'Off is the safe default. Auto Mode bypasses approval and sandbox controls; enable it only for a trusted, isolated project.',
    reliability: "KEEP THINGS RUNNING WHILE YOU'RE AWAY", reliabilityPlain: 'Your agents keep working on a schedule and in live terminals, even when you step away. These settings keep you in the loop and keep things running.', reliabilityTechnical: "Your agents keep working on a schedule and in live terminals. If your Mac fully sleeps those timers pause and catch up the moment you're back — nothing is lost, it may just run late.", keepalive: 'KEEP WORKING WHILE AWAY', keepaliveDesc: 'Strong keep-alive: stops your Mac from sleeping while an agent is live, so schedules and terminals fire on time even when you step away. Uses more battery — best on power. Off by default.', notifications: 'DESKTOP NOTIFICATIONS', notificationsDesc: "Get pinged when an agent needs you or a terminal needs reviving — even while you're away. macOS asks permission the first time one fires.", login: 'OPEN AT LOGIN', loginDesc: 'Relaunch the harness after a reboot so scheduled missions resume on their own. No prompt — applies immediately.', stats: 'SHARE ANONYMOUS USAGE STATS', statsDesc: 'A handful of anonymous events (app opened, agent spawned, feature used) that help improve Munder Difflin — never prompts, code, file paths, or agent output. Full list in TELEMETRY.md; change anytime in Settings.', batteryTitle: 'STAY AWAKE ON POWER (MANUAL)', batteryDesc: 'macOS only lets you set this one yourself. In Battery → Options, turn on “Prevent automatic sleeping when the display is off” (on power adapter) so timers keep firing with the display asleep. Without a sleep-preventing setting the Mac still truly sleeps — work survives and catches up on wake.', battery: 'open Battery settings',
    back: 'back', next: 'next', setup: 'set it up', saving: 'saving...', finish: 'finish', pickError: 'Pick a harness home folder first.'
  },
  hivePicker: { title: 'SELECT A HARNESS CONFIG', description: 'A harness config is the folder where the app keeps everything for one workspace — its settings, your agents and their memory, tasks, triggers, and history. Each config is separate and self-contained, so you can run different setups side by side. Open the one you were working in, switch to another, or start a new one.', current: 'CURRENT', recent: 'RECENT', open: 'open', opening: 'opening…', switch: 'switch →', openExisting: 'open existing config…', createNew: 'create new config…', openingFolder: 'Opening {{folder}} — the app will reload…', switchTitle: 'Switch to {{path}} (reloads the app)', openError: 'Could not open that folder.' },
  michaelBooting: { title: 'CLOCKING IN', message: 'Michael is settling into the corner office and getting the floor ready. Hang tight…' },
  quit: { closingTitle: 'CLOSING TIME', quitTitle: 'QUITTING NOW?', saved: 'FLOOR SAVED — SEE YOU TOMORROW', wrapping: 'WRAPPING UP THE FLOOR', stillWrapping: 'STILL WRAPPING UP…', savedMessage: 'Every agent saved its memory and the orchestrator confirmed the shutdown. The harness closes itself in a moment.', wrappingMessage: 'The orchestrator broadcast closing time. Every worker parks its work, saves its memory, and reports back — the app closes only after the orchestrator confirms nothing will be lost.', workers: '{{count}} / {{total}} WORKERS CONFIRMED', waitingOrchestrator: ' — WAITING FOR THE ORCHESTRATOR', noWorkers: 'NO WORKERS ON THE FLOOR — WAITING FOR THE ORCHESTRATOR', timeout: 'This is taking a while (an agent may be mid-compaction or deep in a tool call). Keep waiting, or force quit and accept the data loss.', cancelBack: 'cancel — back to work', forceQuit: 'force quit now', running: '{{count}} {{agentLabel}} STILL RUNNING', agent: 'AGENT', agents: 'AGENTS', closeWarning: 'Closing the harness will terminate {{sessions}} and discard any unsaved progress they were holding in memory. The conversation history inside each session is lost when the PTY exits.', tip: 'Tip: closing time is the safe way out — the orchestrator has every agent commit its work and save its memory, and the app closes itself once the whole floor has confirmed. No data loss.', keepRunning: 'keep them running', closing: 'closing time', killQuit: 'kill {{target}} & quit', it: 'it', all: 'all', killing: 'killing...', closingError: 'Closing time could not start.' }
} as const;

export const w1_1_zh = {
  status: { idle: '空闲', working: '工作中', waiting: '等待中', needsYou: '需要你', done: '完成', gone: '离线', compacting: '压缩中', looping: '循环中', yourDraft: '你的草稿' },
  onboarding: {
    title: { persona: '欢迎来到 Munder Difflin', welcome: '认识你的办公室', home: '第 1 步 / 共 4 步 · Harness 主目录', homePlain: '第 1 步 / 共 4 步 · 应用的家', orchestrator: '第 2 步 / 共 4 步 · 你的克隆引擎', orchestratorPlain: '第 2 步 / 共 4 步 · 你的克隆', repos: '第 3 步 / 共 4 步 · 你的仓库', reposPlain: '第 3 步 / 共 4 步 · 你的项目', permissions: '第 4 步 / 共 4 步 · 权限与可靠性', done: '准备就绪' },
    cloneTitle: '一个全天候工作的你', cloneIntro: 'Munder Difflin 会把你正在使用的 CLI agent 变成你的克隆：它运行一个长期工作的 Agent 办公室，即使你离开也会继续工作。它管理上下文、记忆、任务、触发器、环境、文件和集成。', localOnly: '一切都在这台机器上运行。', personaPrompt: '首先——你是哪类用户？（我们会据此调整设置）', technical: '我是技术用户', technicalDesc: '我写代码或使用终端。请展示 CLI 命令、参数和模型 ID。', nonTechnical: '我不是技术用户', nonTechnicalDesc: '我来自市场、销售、运营，或刚刚开始。请用易懂的语言解释。', officeTitle: '你的克隆与它运行的办公室', officePlain: '你的克隆运行着一个小型 AI 办公室，你可以在一个屏幕上看到一切。这里包括：', officeTechnical: '你的克隆协调一群持久、可观察、完全本地运行的 AI coding agent。这里包括：',
    feature: { engines: { label: '十种引擎，一个办公室', technical: 'Claude Code、Codex、Grok、Kimi、Antigravity、Qwen、OpenCode、Crush、pi 和 Copilot——同一楼层上的实时 Agent。', plain: '十种 AI 助手——Claude、Codex、Gemini、Grok 等——在同一个办公室并肩工作。' }, clone: { label: 'MICHAEL 是你的克隆', technical: '你的克隆管理办公室：分流请求、分派任务，只把真正需要你的事升级给你。', plain: '你的克隆 Michael 接收请求，把工作交给合适的 Agent，只在重要时刻打扰你。' }, memory: { label: '长期记忆', technical: '每个 Agent 都会记录笔记，并汇总到可搜索的共享 MemPalace。', plain: 'Agent 会记住做过的事，不会每次都从头开始。' }, command: { label: '指挥中心', technical: 'Terminal · Floor · Memory · Activity · Tasks · Triggers 集中在一个控制界面。', plain: '一个仪表盘即可查看工作、Agent 记忆、任务和触发器。' }, guardrails: { label: '安全护栏', technical: '每个 Agent 的 token 预算、steer→constrain→stop 断路器，以及人工审批。', plain: '花费限制和安全停止机制让 Agent 保持可控；重大操作前还可以询问你。' }, hires: { label: '现成的 Agent', technical: '从 Agent Gallery 选择预配置 Agent，一键启动。', plain: '从 Gallery 一键聘用现成 Agent，无需设置。' } },
    homePlain: '创建一个新的空文件夹作为应用的家。应用设置和 Agent 记忆都会保存在这里。比如 ~/HarnessAgents 就很好；如果不存在，我们会替你创建。', homeTechnical: '选择一个文件夹，让 harness 保存自己的文件：Agent 元数据、日志，以及从这里创建的新仓库。例如 ~/HarnessAgents 就是不错的默认值；如果不存在，我们会创建。', pickHome: '选择', createPick: '创建 / 选择', homeHintPlain: '你不需要每天打开这个文件夹；应用会把笔记放在这里，重启后也不会丢失。', homeHintTechnical: '可以把它理解为“市政厅”。Harness 会在那里固定保存 Agent 状态，重启后可继续会话。', orchestratorPlain: 'Michael 是你的克隆：他读取请求、拆分任务并交给合适的 Agent。他是办公室的老板，但你仍然是他的老板。选择驱动他的 AI 引擎。', orchestratorTechnical: 'Michael 是你刚才认识的办公室老板。他会分流请求、分配任务、管理团队，只把真正需要你的事项升级。选择驱动他的引擎和模型，并为他选择更长上下文、更高能力的模型。', cliPlain: 'CLI agent 是运行在电脑上的 AI coding assistant，例如 Claude Code（Anthropic）、Codex（OpenAI）和 Antigravity（Google Gemini）。你的克隆是持续运行、管理整个办公室的那个 Agent。我们推荐 Claude Code 的 Opus 4.8 (1M)，之后可以添加或切换其他选项。', cliTechnical: '每个选项都是你已安装的 CLI engine（Claude Code、Codex、Antigravity/Gemini，或 Qwen 这样的本地代理）。你的克隆 Michael 负责协调整个 hive。推荐：Claude Code · Opus 4.8 · 1M；之后可以为各个 Agent 配置其他 Provider。', recommended: '推荐', model: '模型', modelHint: '这里只设置 Michael 的引擎。之后可以为其他 Agent 使用不同 Provider。', reposPlain: '添加你的项目。项目就是一个文件夹，可以放代码、文档、笔记或 Agent 要处理的任意文件。你可以创建新文件夹或选择已有文件夹，之后随时添加更多。', reposTechnical: '添加 Agent 要工作的仓库。每个文件夹会成为一个项目（办公室中的房间），多个 Agent 可以共享。之后还可以继续添加。', noProjects: '还没有项目。可选——之后可以再添加。', noRepos: '还没有仓库。可选，但建议添加。', addProject: '添加项目', addRepo: '添加仓库', autonomy: 'Agent 可以自主完成多少工作？', autonomyPlain: '让 Agent 自主工作', autonomyTechnical: '自主工作（自动模式）', autoOnPlain: '开启。Agent 会直接执行任务，不会停下来询问——体验最流畅。', autoOffPlain: '关闭。Agent 在修改文件或运行命令前会暂停并询问你。', autoOnTechnical: '开启。Agent 不会暂停——Claude 使用 bypassPermissions，Codex 绕过 approvals + sandbox，等等。', autoOffTechnical: '关闭。每个 Agent 在编辑或执行 shell 命令前都会询问（Claude 默认、codex -a untrusted 等）。', autoHintPlain: '在你信任项目和任务之前请保持关闭。之后可以开启，也可以只为单个 Agent 开启。', autoHintTechnical: '关闭是安全默认值。自动模式会绕过审批和 sandbox 控制；只应在可信、隔离的项目中开启。', reliability: '让工作在你离开时继续运行', reliabilityPlain: '即使你暂时离开，Agent 也会按计划在实时终端中继续工作。这些设置让你保持知情，也让工作继续运行。', reliabilityTechnical: 'Agent 会按计划在实时终端中继续工作。如果 Mac 完全睡眠，计时器会暂停并在你回来时补上——不会丢失，只是可能晚一些。', keepalive: '离开时继续工作', keepaliveDesc: 'Agent 运行时阻止 Mac 睡眠，让计划和终端按时触发。会更耗电，适合接通电源时使用。默认关闭。', notifications: '桌面通知', notificationsDesc: '当 Agent 需要你或终端需要恢复时通知你，即使你暂时离开。macOS 第一次发送通知时会请求权限。', login: '登录时打开', loginDesc: '重启后重新启动 harness，让计划任务自动恢复。无需提示，立即生效。', stats: '分享匿名使用统计', statsDesc: '分享少量匿名事件（打开应用、启动 Agent、使用功能）以帮助改进 Munder Difflin；不会分享提示词、代码、文件路径或 Agent 输出。完整列表见 TELEMETRY.md，可在 Settings 中随时更改。', batteryTitle: '接通电源时保持唤醒（手动）', batteryDesc: 'macOS 只允许你手动设置这一项。在 Battery → Options 中开启“显示器关闭时防止自动睡眠”（接通电源时），这样显示器休眠时计时器仍会触发。没有防睡眠设置时 Mac 仍会真正睡眠；工作不会丢失，会在唤醒后追赶执行。', battery: '打开 Battery 设置', back: '返回', next: '下一步', setup: '开始设置', saving: '保存中...', finish: '完成', pickError: '请先选择 harness 主目录。'
  },
  hivePicker: { title: '选择 Harness 配置', description: 'Harness 配置是应用为一个工作区保存所有内容的文件夹：设置、Agent 及其记忆、任务、触发器和历史记录。每个配置彼此独立，你可以并行运行不同设置。打开上次使用的配置、切换到其他配置，或开始新的配置。', current: '当前', recent: '最近使用', open: '打开', opening: '打开中…', switch: '切换 →', openExisting: '打开已有配置…', createNew: '创建新配置…', openingFolder: '正在打开 {{folder}}，应用即将重新加载…', switchTitle: '切换到 {{path}}（会重新加载应用）', openError: '无法打开该文件夹。' },
  michaelBooting: { title: '正在打卡上班', message: 'Michael 正在进入角落办公室并准备楼层。请稍候…' },
  quit: { closingTitle: '下班时间', quitTitle: '现在退出？', saved: '办公室已保存——明天见', wrapping: '正在收尾办公室', stillWrapping: '仍在收尾…', savedMessage: '每个 Agent 都已保存记忆，协调器也确认了关闭流程。Harness 将很快自行关闭。', wrappingMessage: '协调器已广播下班时间。每个 Worker 会暂停工作、保存记忆并汇报；只有协调器确认不会丢失内容后，应用才会关闭。', workers: '{{count}} / {{total}} 个 Worker 已确认', waitingOrchestrator: '——等待协调器', noWorkers: '办公室没有 Worker——等待协调器', timeout: '这需要一些时间（某个 Agent 可能正在压缩上下文或深入调用工具）。你可以继续等待，或强制退出并接受数据丢失。', cancelBack: '取消——返回工作', forceQuit: '立即强制退出', running: '{{count}} 个 {{agentLabel}} 仍在运行', agent: 'Agent', agents: 'Agent', closeWarning: '关闭 Harness 会终止 {{sessions}}，并丢弃它们保存在记忆中的未保存进度。PTY 退出后，每个会话中的对话历史也会丢失。', tip: '提示：下班时间是安全退出方式——协调器会让每个 Agent 提交工作并保存记忆，整个办公室确认后应用才会自行关闭，不会丢失数据。', keepRunning: '保持运行', closing: '下班时间', killQuit: '终止 {{target}} 并退出', it: '它', all: '全部', killing: '终止中...', closingError: '无法开始下班流程。' }
} as const;
