/** W1.3: Command Center, commands, agents, tasks, messages, and controls. */
const en = {
  residual: { noLiveTerminal: 'This agent has no live terminal. Spawn an agent through "add agent" to use the terminal tab.', switching: 'switching to {{provider}}…', nothingMatchedYet: 'Nothing matched yet.', searchFailed: "Couldn't search: {{error}}" },
  extra: { autoPaused: 'Automatic queue delivery is PAUSED for every agent — messages stay queued until resumed', autoOn: 'Automatic queue delivery is ON for every agent — click to pause the whole floor', ideTip: 'Open the IDE — file editor + git diff', budget: 'budget', ctx: 'ctx', budgetTip: 'CUMULATIVE session usage: {{used}} of {{limit}} tokens{{scope}} — not the context window', contextTip: 'Context window: {{used}} of {{limit}} tokens ({{pct}}%)', noStatus: 'no status tick yet', current: 'current', default: 'default', restarting: 'restarting…', modelRestart: '{{provider}} model (restarts agent)', restartContinue: 'restart & continue', engine: 'engine:', confirmProvider: "This restarts Michael; a conversation on a different engine can't be resumed.", apply: 'apply', tok: 'tok', inputs: 'inputs', cache: 'cache', tokMin: 'tok/min', telemetry: 'live from each agent\'s OpenTelemetry · bars show tokens used vs each agent\'s limit, else the {{budget}} floor budget', defaultBudget: ' (default — set a floor token budget in Settings)', limit: 'limit', privateNote: 'PRIVATE NOTE · {{name}}', noteHelp: 'one line = one bullet · esc to close', addAgent: 'add agent', restoringTip: "Your previous session's agents are being respawned with their original ids, so memory and inboxes reattach.", previousSession: 'Previous session: {{names}}', restoring: 'restoring your team…', restoreTeam: 'restore team ({{count}}) ▴', previousSessionLower: 'previous session', restoreAll: 'restore all', clearAllTitle: 'Clear all queued messages', sendingWhenFree: 'sending when free…', setupDictation: 'Set up dictation', dictationIntro: 'Speak instead of typing. Groq transcribes it, and their free tier covers this — no card, no cost.', createKey: 'Create a free key at', pasteKey: 'Paste it into Settings → Voice → Groq API key', clickVoice: 'Click voice, or hold the right Option key to talk', dictationHelp: 'Hold it ALONE for a moment to start; release to transcribe into the composer, where you can edit before sending. Either Option key works, and Option+key combos still reach the terminal untouched.', setupNow: 'set it up now' },
  fetchIssues: 'Fetch issues',
  commandCenter: { title: 'COMMAND CENTER', subtitle: 'Michael runs the floor', auto: 'auto', paused: 'paused', ide: 'IDE', terminal: 'terminal', monitor: 'monitor', tasks: 'tasks', askMe: 'ask me', triggers: 'triggers', history: 'history', memory: 'memory', graph: 'graph', activity: 'activity', skills: 'skills', workers: 'workers', dispatch: 'DISPATCH — VIA MICHAEL', michaelDecides: 'Michael decides', dispatchPlaceholder: 'Describe the task… (Michael decomposes, writes the card, and assigns)', agents: 'AGENTS', budget: 'budget', context: 'ctx', engine: 'engine:', directories: 'DIRECTORIES', issues: 'ISSUES', noRepos: 'No registered repos.', noIssues: 'No issues fetched yet.', archived: 'ARCHIVED ({{count}})', hide: 'hide', show: 'show', closedAgents: 'closed agents', textSearch: 'TEXT SEARCH (board, tasks, memory)', textSearchPlaceholder: 'Find exact text across hive files…', noMatches: 'Nothing matched.', semanticSearch: 'SEMANTIC SEARCH (MemPalace)', semanticPlaceholder: 'What does the hive know about…', memoryFile: 'MEMORY FILE', noMemory: 'No memory recorded yet.', activitySection: 'ACTIVITY', nothingYet: 'Nothing yet.', board: 'BOARD', emptyBoard: 'The board is empty.', openIde: 'Open the IDE — file editor + git diff', openTerminal: 'Open in Terminal.app', saveLimit: 'Save limit', setLimit: "Set this agent's total token limit", tokens: 'tokens', search: 'search', terminalFullscreen: 'Terminal is open in fullscreen. Press Esc to bring it back.', noTerminal: 'Michael has no live terminal.', killRespawn: 'Kill and respawn this agent, resuming its current conversation — fixes a corrupted/garbled terminal without losing context', killMichael: 'Kill and respawn Michael, resuming the current conversation — fixes a corrupted/garbled terminal without losing context' },
  commandBar: { free: 'free', slash: '/skill', quick: 'quick', blockedPlaceholder: 'Ada needs you...', busyPlaceholder: 'Ada is working...', placeholder: 'Type a command', send: 'send', busy: 'Ada is mid-tool. Queue or hit pause.', approval: 'Approval needed.' },
  agent: { control: 'CONTROL', pause: 'pause', resume: 'resume', pauseTitle: 'Pause — deny every tool call from the next one onward. The agent keeps thinking and talking but cannot read, write or run anything. Takes effect immediately; reversible.', resumeTitle: 'Resume — allow tool calls again. The agent keeps its session and picks up where it stopped.', halt: 'halt', haltTitle: 'Halt — ask the agent to stop cleanly at its next hook boundary.', haltRequested: 'halt requested — stops cleanly at next hook', resumed: 'resumed', paused: 'paused — tool calls will be denied', steerQueued: 'steer queued — delivered on next turn', queuedCount: '{{count}} steer queued', deliveryPaused: 'delivery paused (floor)', halting: 'halting…', steerPlaceholder: 'steer this agent (injected as context, no typing into its terminal)…', steer: 'steer', fullscreen: 'In fullscreen', noPty: 'No PTY', done: 'Done', closeNote: 'Close note editor', notePlaceholder: 'one line per bullet…', noteFor: 'Note for {{name}}', editNote: 'Edit private note', addNote: 'Add private note', workingTasks: 'actively working {{count}} task', workingTasks_other: 'actively working {{count}} tasks', clickToOpen: ' — click to open', restorable: '{{name}} — restorable from last session', dismiss: 'Dismiss {{name}}', openTask: 'open task details', unassigned: 'unassigned' },
  tasks: { task: 'TASK', close: 'close', noDescription: '(no description on this card)', priority: 'Priority {{level}}/5', waiting: 'waiting on YOUR answer — see the ASK ME tab', dismiss: 'dismiss this task (removes it from the board)', dismissLabel: 'dismiss task', open: 'open task details', q: 'Q', a: 'A' },
  askMe: { empty: 'Nothing needs you right now. 🌿', emptyHint: 'When the team blocks a task on your input — a question to answer or a to-do only you can perform — it shows up here (and on the ASK ME board on the floor).', open: 'open the full task detail', dismissTitle: 'dismiss — clear this off the ASK ME board without answering (history kept)', dismissLabel: 'dismiss this ask', answerPlaceholder: "Your answer — or 'done', with the result… (Ctrl+Enter to send)", respond: 'respond & unblock', history: 'VIEW {{count}} EARLIER ANSWER', history_other: 'VIEW {{count}} EARLIER ANSWERS', historyTitle: 'open the task detail with the full Q&A history', blocking: 'BLOCKING {{count}} DOWNSTREAM TASK', blocking_other: 'BLOCKING {{count}} DOWNSTREAM TASKS', more: '… +{{count}} more' },
  queue: { drop: 'DROP TO ATTACH', label: 'QUEUE', busy: '{{name}} is busy — {{count}} queued', paused: 'held — delivery paused floor-wide', draft: "held — {{name}}'s terminal has unsent text on its prompt", picker: 'held — a slash-command picker is open in {{name}}\'s terminal', exited: "held — {{name}}'s terminal has exited", sending: 'sending to {{name}} one-by-one…', clearAll: 'clear all', clearTitle: 'Clear all queued messages', recoverPrompt: 'recover prompt', closePicker: 'close picker', files: 'files', send: 'send', placeholder: 'Message {{name}}', busyPlaceholder: '{{name}} is busy — queue a message', more: 'see more', less: 'see less', sendNow: 'send now', collapse: 'Collapse this message', expand: 'Show the full message', remove: 'Remove from queue', removeAttachment: 'Remove attachment', pausedTitle: 'Auto-delivery is paused for the whole floor. Resume it in the Command Center, or use "send now" on a message below.', attachTitle: 'Deliver this message even though auto-delivery is paused. It moves to the front of the queue and types in as soon as the terminal is free.', dictation: 'Free Flow — dictate into the queue. Click, or hold Option (⌥).', stop: 'Stop & transcribe', transcribing: 'Transcribing…', voice: 'voice', setup: 'Set up dictation', noKey: 'Dictation needs a free Groq API key. Click the info mark for the steps.', info: 'How do I enable dictation?', setupNow: 'set it up now' },
  detail: { openIde: 'Open the IDE — file editor + git diff for {{project}}', openTerminal: 'open Terminal.app at {{cwd}}' }
  ,blocked: { needsYou: 'needs you' }
} as const;
export const w1_3_en = en;
export const w1_3_zh = {
  residual: { noLiveTerminal: '此 Agent 没有运行中的终端。请通过“添加 Agent”启动 Agent 后使用终端标签。', switching: '正在切换到 {{provider}}…', nothingMatchedYet: '尚未匹配到内容。', searchFailed: '搜索失败：{{error}}' },
  extra: { autoPaused: '所有 Agent 的自动投递已暂停 — 消息会留在队列中，直到恢复', autoOn: '所有 Agent 的自动投递已开启 — 点击暂停整个楼层', ideTip: '打开 IDE — 文件编辑器 + git diff', budget: '预算', ctx: '上下文', budgetTip: '会话累计用量：{{used}} / {{limit}} token{{scope}} — 不代表上下文窗口', contextTip: '上下文窗口：{{used}} / {{limit}} token（{{pct}}%）', noStatus: '尚无状态记录', current: '当前', default: '默认', restarting: '重启中…', modelRestart: '{{provider}} 模型（会重启 Agent）', restartContinue: '重启并继续', engine: '引擎：', confirmProvider: '这会重启 Michael；不同引擎的对话无法恢复。', apply: '应用', tok: 'tok', inputs: '输入', cache: '缓存', tokMin: 'tok/min', telemetry: '来自每个 Agent 的 OpenTelemetry · 条形图显示 token 用量与上限，否则显示楼层预算 {{budget}}', defaultBudget: '（默认 — 请在设置中配置楼层 token 预算）', limit: '上限', privateNote: '私有笔记 · {{name}}', noteHelp: '一行 = 一个要点 · Esc 关闭', addAgent: '添加 Agent', restoringTip: '正在使用原始 ID 重新启动上次会话的 Agent，以重新连接记忆和收件箱。', previousSession: '上次会话：{{names}}', restoring: '正在恢复团队…', restoreTeam: '恢复团队（{{count}}）▴', previousSessionLower: '上次会话', restoreAll: '全部恢复', clearAllTitle: '清除所有排队消息', sendingWhenFree: '空闲后发送…', setupDictation: '设置口述', dictationIntro: '无需打字即可口述。Groq 会进行转写，免费额度无需银行卡，也不会收费。', createKey: '创建免费密钥：', pasteKey: '将密钥粘贴到 设置 → 语音 → Groq API 密钥', clickVoice: '点击“语音”，或按住右 Option 键说话', dictationHelp: '单独按住片刻即可开始；松开后会转写到编辑框，你可以编辑后再发送。任一 Option 键都可以，Option 与其他键组合仍会原样传递给终端。', setupNow: '立即设置' },
  fetchIssues: '获取问题',
  commandCenter: { title: '指挥中心', subtitle: 'Michael 管理整个楼层', auto: '自动', paused: '已暂停', ide: 'IDE', terminal: '终端', monitor: '监控', tasks: '任务', askMe: '问我', triggers: '触发器', history: '历史', memory: '记忆', graph: '图谱', activity: '活动', skills: '技能', workers: 'Worker', dispatch: '分派 — 通过 Michael', michaelDecides: '由 Michael 决定', dispatchPlaceholder: '描述任务…（Michael 会拆分、创建卡片并分配）', agents: 'Agent', budget: '预算', context: '上下文', engine: '引擎：', directories: '目录', issues: '问题', noRepos: '没有已登记的仓库。', noIssues: '尚未获取问题。', archived: '已归档（{{count}}）', hide: '隐藏', show: '显示', closedAgents: '已关闭的 Agent', textSearch: '文本搜索（看板、任务、记忆）', textSearchPlaceholder: '在蜂巢文件中查找精确文本…', noMatches: '没有匹配项。', semanticSearch: '语义搜索（MemPalace）', semanticPlaceholder: '蜂巢知道哪些关于…', memoryFile: '记忆文件', noMemory: '尚无记忆记录。', activitySection: '活动', nothingYet: '暂无内容。', board: '看板', emptyBoard: '看板为空。', openIde: '打开 IDE — 文件编辑器 + Git diff', openTerminal: '在 Terminal.app 中打开', saveLimit: '保存上限', setLimit: '设置此 Agent 的 token 总上限', tokens: 'token', search: '搜索', terminalFullscreen: '终端已全屏打开。按 Esc 返回。', noTerminal: 'Michael 没有运行中的终端。', killRespawn: '终止并重启此 Agent，继续当前对话 — 修复终端乱码且不丢失上下文', killMichael: '终止并重启 Michael，继续当前对话 — 修复终端乱码且不丢失上下文' },
  commandBar: { free: '自由', slash: '/技能', quick: '快捷', blockedPlaceholder: 'Ada 需要你…', busyPlaceholder: 'Ada 正在工作…', placeholder: '输入命令', send: '发送', busy: 'Ada 正在调用工具。请排队或暂停。', approval: '需要审批。' },
  agent: { control: '控制', pause: '暂停', resume: '恢复', pauseTitle: '暂停 — 从下一次开始拒绝所有工具调用。Agent 会继续思考和对话，但不能读取、写入或执行任何内容；可立即恢复。', resumeTitle: '恢复 — 允许工具调用。Agent 会保留会话并从停止处继续。', halt: '停止', haltTitle: '停止 — 请求 Agent 在下一个钩子边界安全停止。', haltRequested: '已请求停止 — 将在下一个钩子安全停止', resumed: '已恢复', paused: '已暂停 — 工具调用将被拒绝', steerQueued: '引导已排队 — 下一轮投递', queuedCount: '已排队 {{count}} 条引导', deliveryPaused: '投递已暂停（楼层）', halting: '正在停止…', steerPlaceholder: '引导此 Agent（作为上下文注入，不输入其终端）…', steer: '引导', fullscreen: '已全屏', noPty: '无 PTY', done: '完成', closeNote: '关闭笔记编辑器', notePlaceholder: '每行一条要点…', noteFor: '{{name}} 的笔记', editNote: '编辑私有笔记', addNote: '添加私有笔记', workingTasks: '正在处理 {{count}} 个任务', workingTasks_other: '正在处理 {{count}} 个任务', clickToOpen: ' — 点击打开', restorable: '{{name}} — 可从上次会话恢复', dismiss: '移除 {{name}}', openTask: '打开任务详情', unassigned: '未分配' },
  tasks: { task: '任务', close: '关闭', noDescription: '（此卡片没有描述）', priority: '优先级 {{level}}/5', waiting: '等待你的回答 — 请查看“问我”标签', dismiss: '忽略此任务（从看板移除）', dismissLabel: '忽略任务', open: '打开任务详情', q: '问', a: '答' },
  askMe: { empty: '现在没有需要你的事项。🌿', emptyHint: '当团队因需要你的输入而阻塞任务时——例如需要回答问题或只有你能完成的待办——它会显示在这里（也会显示在楼层的“问我”看板）。', open: '打开完整任务详情', dismissTitle: '忽略 — 不回答并从“问我”看板清除（保留历史）', dismissLabel: '忽略此询问', answerPlaceholder: '你的回答——或输入“完成”并附上结果…（Ctrl+Enter 发送）', respond: '回答并解除阻塞', history: '查看之前的 {{count}} 个回答', history_other: '查看之前的 {{count}} 个回答', historyTitle: '打开任务详情查看完整问答历史', blocking: '阻塞下游 {{count}} 个任务', blocking_other: '阻塞下游 {{count}} 个任务', more: '… 还有 {{count}} 个' },
  queue: { drop: '拖放以附加', label: '队列', busy: '{{name}} 正忙 — 已排队 {{count}} 条', paused: '暂存 — 整个楼层已暂停投递', draft: '暂存 — {{name}} 的终端提示符有未发送文本', picker: '暂存 — {{name}} 的终端打开了斜杠命令选择器', exited: '暂存 — {{name}} 的终端已退出', sending: '正在逐条发送给 {{name}}…', clearAll: '全部清除', clearTitle: '清除所有排队消息', recoverPrompt: '恢复提示符', closePicker: '关闭选择器', files: '文件', send: '发送', placeholder: '给 {{name}} 发消息', busyPlaceholder: '{{name}} 正忙 — 将消息加入队列', more: '查看更多', less: '收起', sendNow: '立即发送', collapse: '收起此消息', expand: '显示完整消息', remove: '从队列移除', removeAttachment: '移除附件', pausedTitle: '整个楼层已暂停自动投递。请在指挥中心恢复，或使用下方消息的“立即发送”。', attachTitle: '即使暂停自动投递也发送此消息。它会移到队首，并在终端空闲后立即输入。', dictation: 'Free Flow — 口述加入队列。点击，或按住 Option（⌥）。', stop: '停止并转写', transcribing: '转写中…', voice: '语音', setup: '设置口述', noKey: '口述需要免费的 Groq API 密钥。点击信息图标查看步骤。', info: '如何启用口述？', setupNow: '现在设置' },
  detail: { openIde: '打开 IDE — {{project}} 的文件编辑器 + git diff', openTerminal: '在 Terminal.app 打开 {{cwd}}' }
  ,blocked: { needsYou: '需要你' }
} as const;
